repo_url: "git@gitlab.emi.u-bordeaux.fr:crispr/snake.git"

scripts:
  infercnv:  "scripts/infercnv.R"
  python_h5: "scripts/python_h5.py"
  mosaic_experimental: "scripts/mosaic_experimental.py"
  karyotapr: "scripts/karyotapR.R"
  compare:   "scripts/compare_results.py"

params:
  infercnv:
    run1_file: "data/RUN1_S1_hFF_WT.dna.h5"
    run2_file: "data/RUN2_S8_hFF_clone_6_KOfluo.dna.h5"
    chrom: "10"
    max_cells: 5000
    min_reads: 100
    max_reads: 50000
    target_norm: 5000
    target_tum: 5000
    seed: 42
    threads: 8
    workdir: "."
    out_dir: "results/infercnv"

  analyse_manuelle:
    wt: "data/RUN1_S1_hFF_WT.dna.h5"
    crispr: "data/RUN2_S8_hFF_clone_6_KOfluo.dna.h5"
    bed: "data/6969-amplicon.bed"
    threshold: 1.5
    distance: 50000
    output: "results/analyse_manuelle_CNV"

  mosaic_experimental:
    wt: "data/RUN1_S1_hFF_WT.dna.h5"
    crispr: "data/RUN2_S8_hFF_clone_6_KOfluo.dna.h5"
    bed: "data/6969-amplicon.bed"
    threshold: 1.5
    distance: 50000
    output: "results/mosaic_experimental"

  karyotapr:
    run1_file: "data/RUN1_S1_hFF_WT.dna.h5"
    run2_file: "data/RUN2_S8_hFF_clone_6_KOfluo.dna.h5"
    design: "data/6969-design-summary.csv"
    out_dir: "results/karyotapr"
    min_reads: 100

  compare: {}
